using Microsoft.EntityFrameworkCore.Migrations;

namespace TweekBook.Data.Migrations
{
    public partial class addedAutogeneratedIdnetityinRefreshToken : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "InValidated",
                table: "RefreshTokens",
                newName: "Invalidated");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameColumn(
                name: "Invalidated",
                table: "RefreshTokens",
                newName: "InValidated");
        }
    }
}
